## An anova test for the os number throughout postnatal development is calculated

In [2]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import statsmodels.stats.multicomp as mc

In [3]:
stats_path = "../measurements/wt-postnatal-development/"

In [4]:
measurements = pd.read_csv(stats_path + "05-c-measurements_filtered-5-and-95-percentile.csv")
measurements

label  age  biol_repl  image_id  maximum        mean      median  \
0          1    8          1         0    803.0  314.092437  282.884766   
1          2    8          1         0   1845.0  620.114058  466.576172   
2          3    8          1         0    564.0  274.831858  253.494141   
3          4    8          1         0    540.0  285.008439  268.189453   
4          5    8          1         0    264.0  234.200000  238.798828   
...      ...  ...        ...       ...      ...         ...         ...   
14896    173   24         28        83    312.0  243.290323  245.492188   
14897    174   24         28        83    685.0  346.677288  326.101562   
14898    175   24         28        83    609.0  337.340530  326.101562   
14899    176   24         28        83    347.0  255.431818  252.820312   
14900    177   24         28        83    345.0  247.479915  245.492188   

       minimum       sigma       sum  ...  \
0        186.0   99.098496  261639.0  ...   
1        174.0  407.194822  467566.0  ...   
2        154.0   91.856545   62112.0  ...   
3        153.0   89.769054   67547.0  ...   
4        202.0   20.192821    5855.0  ...   
...        ...         ...       ...  ...   
14896    179.0   26.596939   60336.0  ...   
14897    187.0   92.460071  424333.0  ...   
14898    188.0   81.507414  343750.0  ...   
14899    193.0   37.513655   11239.0  ...   
14900    176.0   32.455513  117058.0  ...   

       equivalent_spherical_perimeter_rescaled  \
0                                   138.287624   
1                                   129.399980   
2                                    57.955182   
3                                    59.820799   
4                                    13.355085   
...                                        ...   
14896                                61.657763   
14897                               178.734172   
14898                               158.174366   
14899                                19.468019   
14900                                94.825995   

       equivalent_spherical_radius_rescaled  feret_diameter_rescaled  \
0                                  1.885333                 8.107236   
1                                  1.823742                 6.111447   
2                                  1.220513                 3.995289   
3                                  1.240002                 4.669557   
4                                  0.585895                 2.261000   
...                                     ...                      ...   
14896                              1.258897                 5.297594   
14897                              2.143385                 8.551879   
14898                              2.016343                 8.478365   
14899                              0.707387                 1.910894   
14900                              1.561205                 7.951313   

       perimeter_2d_rescaled  major_axis_length_2d_rescaled  \
0                  18.460443                       8.872033   
1                   8.976538                       3.444867   
2                   6.273068                       2.549953   
3                   6.273068                       2.766553   
4                   2.777771                       1.010003   
...                      ...                            ...   
14896               9.737588                       4.460800   
14897              30.066147                       8.226779   
14898              21.955740                       9.303697   
14899               4.002664                       1.622372   
14900              19.177968                       9.110146   

       minor_axis_length_2d_rescaled  surface_area_rescaled  \
0                           2.037236              85.604886   
1                           2.044837              43.541779   
2                           1.312964              21.829812   
3                           1.117553              23.752687   
4                          

In [5]:
measurements_filtered = measurements[["label", "age", "biol_repl", "image_id"]]
measurements_filtered

label  age  biol_repl  image_id
0          1    8          1         0
1          2    8          1         0
2          3    8          1         0
3          4    8          1         0
4          5    8          1         0
...      ...  ...        ...       ...
14896    173   24         28        83
14897    174   24         28        83
14898    175   24         28        83
14899    176   24         28        83
14900    177   24         28        83

[14901 rows x 4 columns]

In [6]:
label = measurements_filtered.groupby("image_id", as_index=False)["label"].size()
label

image_id  size
0          0   105
1          1    72
2          2    72
3          3   108
4          4    93
..       ...   ...
79        79   184
80        80   175
81        81   226
82        82   125
83        83   128

[84 rows x 2 columns]

In [7]:
age = measurements.groupby("image_id", as_index=False)["age", "biol_repl"].max()
age

C:\Users\fsalo\AppData\Local\Temp\ipykernel_17044\4016667725.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  age = measurements.groupby("image_id", as_index=False)["age", "biol_repl"].max()


image_id  age  biol_repl
0          0    8          1
1          1    8          1
2          2    8          1
3          3    8          2
4          4    8          2
..       ...  ...        ...
79        79   24         27
80        80   24         27
81        81   24         28
82        82   24         28
83        83   24         28

[84 rows x 3 columns]

In [8]:
grouped_dataframe = pd.merge(left=label,
                 right=age,
                 how="inner")
grouped_dataframe.rename(columns={"size":"label"}, inplace=True)
grouped_dataframe

image_id  label  age  biol_repl
0          0    105    8          1
1          1     72    8          1
2          2     72    8          1
3          3    108    8          2
4          4     93    8          2
..       ...    ...  ...        ...
79        79    184   24         27
80        80    175   24         27
81        81    226   24         28
82        82    125   24         28
83        83    128   24         28

[84 rows x 4 columns]

In [9]:
label_mean = grouped_dataframe.groupby("biol_repl", as_index=False)["label", "age"].mean()
label_mean

C:\Users\fsalo\AppData\Local\Temp\ipykernel_17044\1154498187.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  label_mean = grouped_dataframe.groupby("biol_repl", as_index=False)["label", "age"].mean()


biol_repl       label   age
0           1   83.000000   8.0
1           2   74.333333   8.0
2           3   83.000000   8.0
3           4   85.666667   8.0
4           5  146.333333  10.0
5           6  166.666667  10.0
6           7  214.333333  10.0
7           8  203.000000  12.0
8           9  199.333333  12.0
9          10  159.666667  12.0
10         11  202.666667  12.0
11         12  159.000000  12.0
12         13  254.666667  14.0
13         14  214.000000  14.0
14         15  168.000000  14.0
15         16  103.666667  14.0
16         17  280.000000  16.0
17         18  252.666667  16.0
18         19  191.666667  16.0
19         20  172.333333  16.0
20         21  235.666667  20.0
21         22  214.666667  20.0
22         23  211.000000  20.0
23         24  199.666667  20.0
24         25  162.666667  24.0
25         26  184.666667  24.0
26         27  185.000000  24.0
27         28  159.666667  24.0

In [10]:
#group by age and retrieve max labels
labels_grouped = label_mean.groupby("age")["label"]

#weird for loop that itterates them all into seperate arrays
groups = [labels_grouped.get_group(group).values for group in labels_grouped.groups]

#show the arrays
groups

[array([83.        , 74.33333333, 83.        , 85.66666667]),
 array([146.33333333, 166.66666667, 214.33333333]),
 array([203.        , 199.33333333, 159.66666667, 202.66666667,
        159.        ]),
 array([254.66666667, 214.        , 168.        , 103.66666667]),
 array([280.        , 252.66666667, 191.66666667, 172.33333333]),
 array([235.66666667, 214.66666667, 211.        , 199.66666667]),
 array([162.66666667, 184.66666667, 185.        , 159.66666667])]

In [11]:
#calculate f value and p value from scipy stats function
f_value, p_value = stats.f_oneway(*groups)

#print the values
print("F-value:", f_value)
print("p-value:", p_value)

F-value: 6.932020992493018
p-value: 0.0003625541485810945


In [14]:
#posthoc results
posthoc_results = mc.MultiComparison(
    label_mean["label"], 
    label_mean["age"]
)

#tukey test
tukey_results = posthoc_results.tukeyhsd()

tukey_results.summary()

<class 'statsmodels.iolib.table.SimpleTable'>

In [15]:
#import custom functions
import sys
sys.path.append("../../../../../01_python_definitions")
from fluorescent_microscopy_analysis import tukey_test

In [17]:
f, p, tukey = tukey_test(label_mean, feature="label")

In [16]:
?tukey_test

Signature: tukey_test(dataframe, feature)
Docstring: calculates a a tukey test of a features in dependency of the age requires a grouped dataframe with means 
File:      c:\users\fsalo\documents\github\01_python_definitions\fluorescent_microscopy_analysis.py
Type:      function